### PR TITLE
Modify the encoding of AssemblyInfo.cpp

### PR DESCRIPTION
**Pull request by xiaoqingxing**
In some language such as Chinese,  the diacritics of comment in file may cause compile warning, which will cause compile error because of the project setting.

### CODE REVIEW

**Comment by xiaoqingxing** [comment]
Why this pull request is closed with force-pushed, without code merged nor rejected?
Perhaps its a miss-operation?

**Comment by lucasg** [comment]
Sorry I though I'd merged your PR already. I'll reopen it and try to process it tonight.

**Comment by ranolfi** [comment]
@xiaoqingxing perhaps you can rebase your commit on top of a clean git tree? Should make this merging easier.

**Comment by lucasg** [comment]
the commit has been cherry-picked as c166e4284fe483846b63e8cb1a342361b454bc83 in the master, closing this PR

**Pull request closed without merging**
