### PR TITLE
Manifest Dependencies for Arm Bug fix 

### PR DESCRIPTION
**Pull request by sj6219**
The minor bug in the arm os machine has been corrected. I tested it on a Surface Pro X and checked it to see if it worked well.

### CODE REVIEW

**Comment by lucasg** [comment]
Thanks ! that's really cool !
Dependencies runs on the Surface X via the x86 emulator right ? (I should get a surface one day too 😞 )

Before I merge your PR into the master, I've also merged https://github.com/lucasg/Dependencies/pull/96 in the same branch : https://github.com/lucasg/Dependencies/commits/arm

Can you test real quick if Dependencies run correctly and can parse ARM PE binairies, pretty please ? Here's the build artifacts if you don't want to rebuild everything : https://ci.appveyor.com/project/lucasg/dependencies/builds/33082156

Anyway, thanks again !

**Comment by sj6219** [comment]
Once again, I built the program and checked that it worked well on the surface pro x machine.
As you said, x86 version was tested in the emulation environment.

You only need to change the "DependenciesLib\SxsManifest.cs" file.
The remaining files were slightly modified due to conflicts between the latest WDK and SDK during the build process.

**Comment by hmartinez82** [comment]
@lucasg  You should also merge https://github.com/lucasg/Dependencies/pull/96 , that way, even when running Dependencies in x86 emulation, the UI will show correctly the Image Type as ARM64 when looking at native ARM64 DLLs.

**Comment by sj6219** [comment]
I found some new bugs and solved them.

It was also confirmed that ARM Thumb-2 and ARM64 were displayed.

**Comment by lucasg** [comment]
Merged.

Once again, thanks a lot to both of you ! I'll make a new release in the following days to celebrate the fact that `Dependencies` runs on ARM :)

@sj6219, if you experience any bugs when running `Dependencies` on your Surface X, feel free to open a ticket on the issue tracker. I might not be able to fix them quickly since I don't have a way to test easily, but at least there is a papertrail.

Cheers

**Pull request closed without merging**
